name: Build and Deploy WAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Build with Maven
      run: |
        ./mvnw clean package

    - name: Upload WAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: target/*.war
